name: train-model
on:
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run training (smoke)
        run: |
          python train/train.py --data-dir data/chips --epochs 2 --batch-size 2
      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: runs/model_inference.pth
